version: '1'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/dockerfile
    ports:
      -"50080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

db:
  image: mysql/mysql-server:5.5.62
  ports:
    - ./dockerfile/db/my.conf:/etc/mysql/conf.d/my.conf
    - ./docker/db/mysql_data:/var/lib/mysql
  env_file:
    - ./docker/db/db-variables.env
